packages:
  - apps/*
  - packages/*

catalogs:
  default:
    "@types/node": ^24.10.13
    temporal-polyfill: ^0.3.0
    tsdown: ^0.19.0
    typescript: ^5.9.3
    sharp: ^0.34.5

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd

overrides:
  "@types/node": catalog:default
  temporal-polyfill: catalog:default
  tsdown: catalog:default
  typescript: catalog:default
  sharp: catalog:default
  "@typescript-eslint/utils": ">=8.55.0"

sharedWorkspaceLockfile: true
