packages:
  - apps/*
  - packages/*

catalogs:
  default:
    '@types/node': ^24.9.2
    tsdown: ^0.17.3
    typescript: ^5.9.3

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd

overrides:
  '@types/node': catalog:default
  tsdown: catalog:default
  typescript: catalog:default

sharedWorkspaceLockfile: true
