packages:
  - apps/*
  - packages/*

allowBuilds:
  "@apollo/protobufjs": true
  "@nestjs/core": true
  "@prisma/client": true
  "@prisma/engines": true
  "@scarf/scarf": true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true

blockExoticSubdeps: true

catalogs:
  default:
    "@types/node": ^24.12.2
    sharp: ^0.34.5
    temporal-polyfill: ^0.3.2
    tsdown: ^0.21.10
    typescript: ^5.9.3

injectWorkspacePackages: true

linkWorkspacePackages: true

minimumReleaseAge: 1440

nodeOptions: ${NODE_OPTIONS:- } --experimental-transform-types
  --no-warnings=ExperimentalWarning --use-system-ca

overrides:
  "@types/node": catalog:default
  sharp: catalog:default
  temporal-polyfill: catalog:default
  tsdown: catalog:default
  typescript: catalog:default

sharedWorkspaceLockfile: true

syncInjectedDepsAfterScripts:
  - build

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - reselect@5.1.1
  - rollup@2.80.0
  - chokidar@4.0.3
