packages:
  - apps/*
  - packages/*

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - workerd

overrides:
  '@types/node': ^24.7.2
  tsdown: ^0.15.6
  typescript: ^5.9.3

sharedWorkspaceLockfile: true
