packages:
  - apps/*
  - packages/*

catalogs:
  default:
    "@types/node": ^24.12.2
    temporal-polyfill: ^0.3.2
    tsdown: ^0.21.7
    typescript: ^5.9.3
    sharp: ^0.34.5

nodeOptions: "${NODE_OPTIONS:- } --experimental-strip-types
  --no-warnings=ExperimentalWarning --use-system-ca"

linkWorkspacePackages: true
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  "@apollo/protobufjs": true
  "@nestjs/core": true
  "@prisma/client": true
  "@prisma/engines": true
  "@scarf/scarf": true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true

overrides:
  "@types/node": catalog:default
  temporal-polyfill: catalog:default
  tsdown: catalog:default
  typescript: catalog:default
  sharp: catalog:default

sharedWorkspaceLockfile: true

# Supply chain security settings
blockExoticSubdeps: true
minimumReleaseAge: 1440 # 1 day
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - reselect@5.1.1
  - rollup@2.80.0
  - chokidar@4.0.3
