packages:
  - apps/*
  - packages/*

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - workerd

overrides:
  "@types/node": catalog:default
  tsdown: catalog:default
  typescript: catalog:default

catalogs:
  default:
    "@types/node": ^24.9.2
    typescript: ^5.9.3
    tsdown: ^0.15.9

sharedWorkspaceLockfile: true
