import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { lingui } from "@lingui/vite-plugin";
import { VitePWA, VitePWAOptions } from "vite-plugin-pwa";
import manifestSRIPlugin from "@oktomusic/vite-sri-manifest";

const MB = 1024 * 1024;

const viteConfigPWA: Partial<VitePWAOptions> = {
  // Configure our own SW
  strategies: "injectManifest",
  srcDir: "src/sw",
  filename: "sw.ts",
  injectManifest: {
    rollupFormat: "es",
    globPatterns: ["**/*.{js,css,html,svg,png,ico}"],
    maximumFileSizeToCacheInBytes: 10 * MB,
  },

  // SW injection
  injectRegister: false,
  registerType: "autoUpdate",

  // Manifest is backend-generated
  // Assets are generated by hand from configuration
  manifest: false,
  pwaAssets: {
    disabled: true,
  },

  workbox: {
    globPatterns: ["**/*.{js,css,html,svg,png,ico}"],
    cleanupOutdatedCaches: true,
    clientsClaim: true,
  },

  // Enable SW in dev mode
  devOptions: {
    enabled: true,
    navigateFallback: "index.html",
    type: "module",
  },
};

export default defineConfig({
  plugins: [
    react({
      babel: {
        plugins: [
          "babel-plugin-react-compiler",
          "@lingui/babel-plugin-lingui-macro",
        ],
        presets: ["jotai/babel/preset"],
      },
    }),
    tailwindcss(),
    lingui(),
    VitePWA(viteConfigPWA),
    manifestSRIPlugin(),
  ],
  server: {
    cors: {
      origin: "http://localhost:3000",
      methods: ["GET"],
    },
    port: 5173,
    strictPort: true,
    hmr: {
      protocol: "ws",
      port: 5173,
    },
    origin: "http://localhost:5173",
  },
  build: {
    manifest: true,
    rollupOptions: {
      input: "src/main.tsx",
    },
    outDir: "dist",
  },
  base: "/",
});
