---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      use_cache:
        description: "Use build cache"
        required: true
        type: boolean
        default: true

env:
  VITEPRESS_HOSTNAME: https://oktomusic.afcms.dev

jobs:
  app-backend:
    name: "@oktomusic/backend"
    runs-on: ubuntu-latest
    needs:
      - pkg-lyrics
      - pkg-playlists
      - pkg-metaflac-parser
      - pkg-api-schemas
      - pkg-vibrant
      - pkg-meta-tags
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build @oktomusic/api-schemas
        run: pnpm --filter "@oktomusic/api-schemas" build

      - name: Build @oktomusic/metaflac-parser
        run: pnpm --filter "@oktomusic/metaflac-parser" build

      - name: Build @oktomusic/lyrics
        run: pnpm --filter "@oktomusic/lyrics" build

      - name: Build @oktomusic/vibrant
        run: pnpm --filter "@oktomusic/vibrant" build

      - name: Build @oktomusic/meta-tags
        run: pnpm --filter "@oktomusic/meta-tags" build

      - name: Prisma generate
        run: pnpm --filter "@oktomusic/backend" run db:generate

      - name: Build
        run: pnpm --filter "@oktomusic/backend" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/backend" run lint

      - name: Tests
        run: |
          pnpm --filter "@oktomusic/backend" run test

  app-frontend:
    name: "@oktomusic/frontend"
    runs-on: ubuntu-latest
    needs:
      - pkg-vite-sri-manifest
      - pkg-lyrics
      - pkg-api-schemas
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build @oktomusic/vite-sri-manifest
        run: pnpm --filter "@oktomusic/vite-sri-manifest" build

      - name: Build @oktomusic/api-schemas
        run: pnpm --filter "@oktomusic/api-schemas" build

      - name: Build
        run: pnpm --filter "@oktomusic/frontend" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/frontend" run lint

      - name: Tests
        run: |
          pnpm --filter "@oktomusic/frontend" run test

  pkg-vite-sri-manifest:
    name: "@oktomusic/vite-sri-manifest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/vite-sri-manifest" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/vite-sri-manifest" run lint

  pkg-lyrics:
    name: "@oktomusic/lyrics"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/lyrics" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/lyrics" run lint

      - name: Tests
        run: |
          pnpm --filter "@oktomusic/lyrics" run test

  pkg-playlists:
    name: "@oktomusic/playlists"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/playlists" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/playlists" run lint

      - name: Tests
        run: |
          pnpm --filter "@oktomusic/playlists" run test

  pkg-metaflac-parser:
    name: "@oktomusic/metaflac-parser"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/metaflac-parser" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/metaflac-parser" run lint

      - name: Tests
        run: |
          pnpm --filter "@oktomusic/metaflac-parser" run test

  pkg-api-schemas:
    name: "@oktomusic/api-schemas"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/api-schemas" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/api-schemas" run lint

  pkg-vibrant:
    name: "@oktomusic/vibrant"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/vibrant" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/vibrant" run lint

      - name: Tests
        run: |
          pnpm --filter "@oktomusic/vibrant" run test

  pkg-meta-tags:
    name: "@oktomusic/meta-tags"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm --filter "@oktomusic/meta-tags" build

      - name: Lint
        run: |
          pnpm --filter "@oktomusic/meta-tags" run lint

      - name: Tests
        run: |
          pnpm --filter "@oktomusic/meta-tags" run test

  website:
    name: "@oktomusic/website"
    runs-on: ubuntu-latest
    needs:
      - pkg-meta-tags
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build @oktomusic/meta-tags
        run: pnpm --filter "@oktomusic/meta-tags" build

      - name: Build website
        run: pnpm --filter "@oktomusic/website" run build

  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    needs: website
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    permissions:
      contents: read
      deployments: write
    concurrency:
      group: deploy-website
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Build @oktomusic/meta-tags
        run: pnpm --filter "@oktomusic/meta-tags" build

      - name: Build website
        run: pnpm --filter "@oktomusic/website" run build

      - name: Build & Deploy Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./apps/website/.vitepress/dist --project-name=oktomusic
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Docker
    uses: docker/github-builder/.github/workflows/build.yml@v1
    needs:
      - app-backend
      - app-frontend
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
      set-meta-annotations: true
      set-meta-labels: true
      meta-annotations: |
        org.opencontainers.image.title=Oktomusic
        org.opencontainers.image.description=Music streaming server
        org.opencontainers.image.authors=AFCMS <afcm.contact@gmail.com>
        org.opencontainers.image.licenses=AGPL-3.0-only
        org.opencontainers.image.source=https://github.com/oktomusic/oktomusic
        io.artifacthub.package.readme-url=https://raw.githubusercontent.com/oktomusic/oktomusic/refs/heads/master/docs/artifacthub/container.md
        io.artifacthub.package.category=skip-prediction
        io.artifacthub.package.keywords=music,server,streaming
        io.artifacthub.package.license=AGPL-3.0-only
        io.artifacthub.package.maintainers=[{"name":"AFCMS","email":"afcm.contact@gmail.com"}]
      meta-labels: |
        org.opencontainers.image.title=Oktomusic
        org.opencontainers.image.description=Music streaming server
        org.opencontainers.image.authors=AFCMS <afcm.contact@gmail.com>
        org.opencontainers.image.licenses=AGPL-3.0-only
        org.opencontainers.image.source=https://github.com/oktomusic/oktomusic
        io.artifacthub.package.readme-url=https://raw.githubusercontent.com/oktomusic/oktomusic/refs/heads/master/docs/artifacthub/container.md
        io.artifacthub.package.category=skip-prediction
        io.artifacthub.package.keywords=music,server,streaming
        io.artifacthub.package.license=AGPL-3.0-only
        io.artifacthub.package.maintainers=[{"name":"AFCMS","email":"afcm.contact@gmail.com"}]
      sbom: true
      sign: auto
      cache: true
      cache-mode: max
      distribute: true
      fail-fast: false
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  typst-docs:
    name: Typst Documents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Typst
        uses: typst-community/setup-typst@v5

      - name: Build Project Report
        run: typst compile --root . docs/certification/oktomusic_project_report_fr.typ docs/certification/oktomusic_project_report_fr.pdf

      - name: Build Project Presentation
        run: typst compile --root . docs/certification/oktomusic_project_presentation_fr.typ docs/certification/oktomusic_project_presentation_fr.pdf

      - name: Upload PDFs as Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: oktomusic_certification_documents
          path: |
            docs/certification/oktomusic_project_report_fr.pdf
            docs/certification/oktomusic_project_presentation_fr.pdf
