---
name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup PNPM
        uses: pnpm/setup@v2
        with:
          cache: true
          install: true

      - name: Database Codegen
        continue-on-error: true
        run: pnpm --filter "@oktomusic/backend" run db:generate

      - name: Initial Build
        continue-on-error: true
        run: pnpm run --filter "./packages/*" build
