---
name: Zizmor

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "27 2 * * *"

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@v0.6.2
